[package]
name = "raffia-playground"
version = "0.1.0"
authors = ["Pig Fang <g-plane@hotmail.com>"]
repository = "https://github.com/g-plane/raffia-playground"
license = "MIT"
publish = false

[lib]
path = "wasm/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
